<a href="https://colab.research.google.com/github/joshuwaifo/A-Bible-Pre-trained-Transformer-Model/blob/main/BPETokeniser_Tiktoken_BibleGPT_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

After pre-training stage: document completer

It babbles the datasource (ie Bible - here, Internet)

So if you give it a question, it would probably respond with more questions

Produces undefined behaviour

- Answering question with other questions

- It is unaligned

Unaligned

The next stage therefore is to align it: fine-tune it to be an assistant


There are 3 steps to this inspired by the ChatGPT blog post: https://openai.com/index/chatgpt/



In [ ]:
# collect training data
# that looks specifically like what an assistant would do

# documents that have the format where:
# the question is on top and
# the answer is below

# and a large number of such structure
# order of maybe thousands of examples

After collecting training data

- Fine tune the model to only focus on documents that look like such

This starts to slowly align the model

- ie expect a question at the top

- and expect to complete the answer


In [ ]:
# These very large models are very sample efficient during the fine-tuning
# step 1 then ends aka finetuning ends

Step 2:

Let the model respond

Different raters look at the different responses

And rank them for their preferences as to which one is better than the other

They use this to train a reward model

So they can predict using a different (neural) network:

- how much of any candidate response would be desirable

aka a desirability of response model

This is the reward model


In [ ]:
# After reward model obtained

# Run PPO

# PPO is a form of a policy gradient reinforcement learning optimiser

# This is to fine tune the sampling policy

# so that the answers that the GPT generates

# are expected to score a high reward

# in accordance with the reward model



This is the whole aligning / fine-tuning stage

with multiple steps

Taking the model from being a document completer

To a question answerer!!!

Normally the data used in this aligning / fine-tuning stage is not available publicly

For OpenAI it is internal, thereby making it much harder to replicate this align

In [ ]:
# Nano GPT: pre-training stage only
# ChatGPT: pre-training stage + post-training stage (fine-tuning, reward model, PPO RL to improve sampling of answers from the model)

To summarise:

- trained a decoder only transformer (inspired by the paper: Attention Is All You Need, 2017) => "a GPT-3 like but (10,000 to million times) simpler model using minimal resources"

- trained on a Bible NASB entire txt file => somewhat sensible results, would have been nice to get actual metrics

- git log commits can be found in Andrej Karpathy's repo to track how progress was made from the get go

- fine-tuning stage not implemented yet (ie solving a particular task, aligned in a specific way, detect sentiment etc.) => typically done with simple supervised fine tuning or supervised fine tuning + reward modelling + policy sampling as done in ChatGPT

- HOWEVER, this stage the pre-training stage in my hypothesis using an already built internet based document blabbler is a good proxy for determining is content is novel by inverting the softmax stage and weighting the prediction probabilities with a given sample/seed text - possible product

Andrej Karpathy ends, Build a Large Language Model (from Scratch) book by Sebastian Raschka begins

In [ ]:
!wget https://raw.githubusercontent.com/tushortz/variety-bible-text/master/bibles/nasb.txt

--2024-08-12 07:51:39--  https://raw.githubusercontent.com/tushortz/variety-bible-text/master/bibles/nasb.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4685837 (4.5M) [text/plain]
Saving to: ‘nasb.txt’

nasb.txt            100%[===================>]   4.47M  --.-KB/s    in 0.06s   

2024-08-12 07:51:40 (69.8 MB/s) - ‘nasb.txt’ saved [4685837/4685837]



Tokeniser

- encode method: takes in natural text, splits it into individual tokens, converts tokens into token ID's via a vocabulary (tokenizer.encode(text))

- decode method: takes in token IDs, converts token IDs into text tokens, concatenates the text tokens onto natural text (tokenizer.decode(ids))

Vocabulary and Inverse vocabulary

In [ ]:
with open("nasb.txt", "r", encoding="utf-8") as f:
    raw_text = f.read()
print("Total number of character:", len(raw_text))
print(raw_text[:99])

Total number of character: 4623633
In the beginning God created the heavens and the earth. -- genesis 1:1
.
The earth was formless and


Extend vocabulary with additional special tokens

Add special tokens to a vocabulary to deal with certain contexts

- <|unk|> token to represent new and unknown words that were not part of the training data and thus not a part of the existing vocabulary

- <|endoftext|> token to seperate two unrelated text sources

In [ ]:
# Byte Pair Encoding tokenisation scheme used by Llama, GPT-3 etc.
!pip install tiktoken
from importlib.metadata import version
import tiktoken
print("tiktoken version:", version("tiktoken"))

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 21.4 MB/s eta 0:00:00
tiktoken version: 0.7.0


Independent text source

<|endoftext|> token act as markers signalling start or end of a particular segment allowing for more effective processing and understanding by the LLM

Prepend it (add it to the start) of each subsequent (following) text source

Depending on the LLM tokens can be

- [BOS]: Beginning of sequence

- [EOS]: End of sequence

- [PAD]: padding


Byte pair encoding tokeniser doesn't use <|unk|> token

In [ ]:
tokenizer = tiktoken.get_encoding("gpt2")

BPE tokenisers break down unknown words into subwords and individual characters

This allows the BPE tokeniser to parse any word and doesn't need to replace unknown words with special tokens, like <|unk|>

In [ ]:
# convert string into token ids
text = "Hello, do you like tea? <|endoftext|> In the sunlit terraces of someunknownPlace."
integers = tokenizer.encode(text, allowed_special={"<|endoftext|>"})
print(integers)

[15496, 11, 466, 345, 588, 8887, 30, 220, 50256, 554, 262, 4252, 18250, 8812, 2114, 286, 617, 34680, 27271, 13]


Call the BPE tokeniser on the Word "Akwirw ier" and print the individual token IDs

In [ ]:
resulting_integers = tokenizer.encode("Akwirw ier")
print(resulting_integers)

[33901, 86, 343, 86, 220, 959]


Call decode on resulting integers to produce a mapping of each integer (token Ids) to token texts

In [ ]:
# note that the input to decode has to be a list even if it is a list of one integer element
tokens = [tokenizer.decode([integer]) for integer in resulting_integers]
print(tokens)

['Ak', 'w', 'ir', 'w', ' ', 'ier']


Call decode method of token ids (resulting integers) to reconstruct orginal input

In [ ]:
original_input = tokenizer.decode(resulting_integers)
print(original_input)

Akwirw ier


During training we mask out all words that are past the target (past the next word to ideally be predicted)



In [ ]:
# Encode the Bible using the BPE tokeniser
enc_text = tokenizer.encode(raw_text)
print(len(enc_text))

1249848


1.249848 million tokens in the data set

In [ ]:
# tensor containing the inputs: x
# tensor containing the targets: y

# use PyTorch's built in Dataset and DataLoader classes

import torch
from torch.utils.data import Dataset, DataLoader

#  defines how individual rows are fetched from the dataset
class GPTDatasetV1(Dataset):
    def __init__(self, txt, tokenizer, max_length, stride):
        self.input_ids = []
        self.target_ids = []

        token_ids = tokenizer.encode(txt)

        for i in range(0, len(token_ids) - max_length, stride):
            input_chunk = token_ids[i:i + max_length]
            target_chunk = token_ids[i + 1: i + max_length + 1]
            self.input_ids.append(torch.tensor(input_chunk))
            self.target_ids.append(torch.tensor(target_chunk))

    def __len__(self):
        return len(self.input_ids)

    def __getitem__(self, idx):
        return self.input_ids[idx], self.target_ids[idx]


Data loader to generate batches with input-output pairs

In [ ]:
def create_dataloader_v1(txt, batch_size=4, max_length=256,
        stride=128, shuffle=True, drop_last=True, num_workers=0):
    tokenizer = tiktoken.get_encoding("gpt2")
    dataset = GPTDatasetV1(txt, tokenizer, max_length, stride)
    dataloader = DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=shuffle,
        drop_last=drop_last,
        num_workers=0
    )

    return dataloader

Test data loader on Bible txt

In [ ]:
dataloader = create_dataloader_v1(
    raw_text, batch_size=1, max_length=4, stride=1, shuffle=False)
data_iter = iter(dataloader)
first_batch = next(data_iter)
print(first_batch) # looks good

[tensor([[ 818,  262, 3726, 1793]]), tensor([[ 262, 3726, 1793, 2727]])]


If stride is equal to input window size we can prevent overlaps between the batches

A stride of 1 moves the input field by 1 position

Context size = max_length here which is also equivalent somewhat to timesteps

In [ ]:
# Preparing the input text for an LLM involves

# Input text: "This is an example."
# tokenising text: | This | is | an | example | . |
# converting text tokens to token IDs: | 40134 | 2052 | 133 | 389 | 12 |
# converting token IDs into vector embedding vectors: token embedding vectors
# creating input token embeddings

# GPT-like decoder only transformer
# Postprocessing steps
# Output text




Example

In [ ]:
input_token_ids = torch.tensor([2, 3, 5, 1])


vocab_size = 6
output_dim = 3


torch.manual_seed(123)
embedding_layer = torch.nn.Embedding(vocab_size, output_dim)
print(embedding_layer.weight) # embedding layer's underlying weight matrix

Parameter containing:
tensor([[ 0.3374, -0.1778, -0.1690],
        [ 0.9178,  1.5810,  1.3010],
        [ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-1.1589,  0.3255, -0.6315],
        [-2.8400, -0.7849, -1.4096]], requires_grad=True)


Weight matrix of embedding layer contains small random values

These values are optimised during LLM training as part of the LLM optimisation itself

Weight matrix has 6 rows and 3 columns

One row for each of the possible 6 tokens in the vocabulary

One column for each of the three embedding dimensions

In [ ]:
# apply embedding layer to a token id
print(embedding_layer(torch.tensor([3])))

tensor([[-0.4015,  0.9666, -1.1481]], grad_fn=<EmbeddingBackward0>)


This is identical to the 4th row in the weight matrix above

Essentially it is a look up operation that retrieves rows from the embedding layer's weight matrix via a token id

In [ ]:
# Apply embedding layer to all 4 input ids defined earlier
print(embedding_layer(input_token_ids))

tensor([[ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-2.8400, -0.7849, -1.4096],
        [ 0.9178,  1.5810,  1.3010]], grad_fn=<EmbeddingBackward0>)


This verifies the idea of the lookup operation mentioned previously

In [ ]:
# Continue from Figure 2.16



Finetuning Open-Source LLMs YouTube video

In [ ]:
# Using pretrained language models

Chain of thought prompting

In [ ]:
# Retrieval augmented generation

# optionally consult external documents

# steps:
# query
# embed the query
# external document
# extract chunk like text passages from the document
# create embeddings
# sometimes store these embeddings in a vector database
# depending on whether we are creating them on the fly or not
# generate response by combining embedding from the query and the embeddings searched over that are appropriate from the database
# response then includes passages from the document

# useful when providing pre-written or certain responses to a user based on some documentation





Finetuning LLMs

Applications

- finetuning a large language model classifier (ie documents, whether an email is spam or not or categorising newspaper articles, internal documents, predicting whether content is toxic etc.)

Common approaches

1. efficient and cheap: feature based approach

- labelled dataset
- take a pre-trained transformer (LLM)
- keep the model frozen
- the purpose being to just extract embeddings from the model
- train a classifier based on the embeddings (ie support vector machine, logistic regression etc.)
~75% example using BERT

2. similar to 1

- with addition of attaching one or more hidden layers and an output layer to a pre-trained transformer backbone
- transformer is still frozen
- only just updating the new layers added
- normally involves 2 or more layers
- more expensive than method 1 (feature based approach)
~90% example using BERT

3. most expensive
- update all the layers of the transformer
- updating the complete model
- highest computational cost
- typically best performance
~93% example using BERT

Useful to go in that order and see what the results are looking like





In [ ]:
# Instruction finetuning

# finetuning a large language model pre-trained to carry out specific instructions

# assume already having a pre-trained language model
# train to create outputs ie (instruction -> inputN -> outputN) for an instruction provided by a user

# instruction can be anything
# ie write a limerick about a pelican
# translate a text
# summarise a text
# perform basic math
# any consistent type of task
# any consistent type of question

# optionally we can perform additional "input"
# using the approach to do classification
# for example
# instruction: Identify the odd one out from the group
# input: Carrot, Apple, Banana, Grape
# output: Carrot


Parameter Efficient Finetuning: PEFT

- making the supervised finetuning process a bit cheaper

Methods or techniques:

Classes:
- Reparametrization based
- Selective
- Soft prompts
- Adapters
- Additive

Approaches:

- LoRa (Reparametrization based): most popular. Stands for Low-rank adaptation


In [ ]:
# Low Rank Adaptation

# Takes a large weight matrix update
# And factorises it
#

Regular fine-tuning

- pretrained weights of a model

Go from inputs

-> Want to produce output embeddings

This involvess a large weight matrix